[build]
    command = "echo build netlify"
    functions = "functions"
[functions]
    external_node_modules = ["express"]
    node_bundler = "esbuild"
    # Ajout de la documentation de l'interface logicielle
    included_files = ["env/development.env", "./functions/index.html"]
node_bundler = "esbuild" 
[[redirects]]
    force = true
    from = "/*"
    status = 200
    to = "/.netlify/functions/api/:splat"