[build]
    command = "echo build netlify"
    functions = "functions"
[functions]
    external_node_modules = ["express"]
    node_bundler = "esbuild"
    included_files = ["env/development.env"] 
[[redirects]]
    force = true
    from = "/*"
    status = 200
    to = "/.netlify/functions/api/:splat"